"""Scheduling Repository Protocols."""

from __future__ import annotations

from datetime import date, datetime
from typing import Optional, Protocol
from uuid import UUID

from odontoflow.scheduling.domain.models import Appointment, ProviderSchedule


class AppointmentRepository(Protocol):
    async def get_by_id(self, appointment_id: UUID) -> Optional[Appointment]: ...
    async def save(self, appointment: Appointment) -> None: ...
    async def update(self, appointment: Appointment) -> None: ...
    async def get_by_date_range(
        self, provider_id: UUID, start: datetime, end: datetime,
    ) -> list[Appointment]: ...
    async def get_by_patient(self, patient_id: UUID) -> list[Appointment]: ...
    async def get_day_schedule(self, provider_id: UUID, day: date) -> list[Appointment]: ...


class ProviderScheduleRepository(Protocol):
    async def get_by_provider(self, provider_id: UUID) -> Optional[ProviderSchedule]: ...
    async def save(self, schedule: ProviderSchedule) -> None: ...
    async def update(self, schedule: ProviderSchedule) -> None: ...
    async def get_all(self) -> list[ProviderSchedule]: ...
