"""IAM Repository Protocols — interfaces that infrastructure implements."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from odontoflow.iam.domain.models import Tenant, TenantMembership, User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def save(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...


class TenantRepository(Protocol):
    async def get_by_id(self, tenant_id: UUID) -> Tenant | None: ...
    async def get_by_slug(self, slug: str) -> Tenant | None: ...
    async def save(self, tenant: Tenant) -> None: ...
    async def update(self, tenant: Tenant) -> None: ...


class MembershipRepository(Protocol):
    async def get_by_user_and_tenant(self, user_id: UUID, tenant_id: UUID) -> TenantMembership | None: ...
    async def get_by_tenant(self, tenant_id: UUID) -> list[TenantMembership]: ...
    async def get_by_user(self, user_id: UUID) -> list[TenantMembership]: ...
    async def save(self, membership: TenantMembership) -> None: ...
    async def delete(self, membership_id: UUID) -> bool: ...
