"""Treatment Repository Protocols."""
from __future__ import annotations

from typing import Optional, Protocol
from uuid import UUID

from odontoflow.treatment.domain.models import ProcedureCatalog, TreatmentPlan


class TreatmentPlanRepository(Protocol):
    async def get_by_id(self, plan_id: UUID) -> Optional[TreatmentPlan]: ...

    async def get_by_patient(self, patient_id: UUID) -> list[TreatmentPlan]: ...

    async def save(self, plan: TreatmentPlan) -> None: ...

    async def update(self, plan: TreatmentPlan) -> None: ...

    async def delete(self, plan_id: UUID) -> None: ...


class ProcedureCatalogRepository(Protocol):
    async def get_by_id(self, procedure_id: UUID) -> Optional[ProcedureCatalog]: ...

    async def get_by_tuss_code(self, tuss_code: str) -> Optional[ProcedureCatalog]: ...

    async def get_all(self, category: Optional[str] = None) -> list[ProcedureCatalog]: ...

    async def save(self, procedure: ProcedureCatalog) -> None: ...

    async def update(self, procedure: ProcedureCatalog) -> None: ...
